default:
  - API
  - OFFICIAL_BULK_EXPORT
  - OFFICIAL_DOWNLOAD
  - OFFICIAL_MIRROR
  - ARCHIVE
  - SEARCH_INDEX
  - LEGISLATIVE_ATTACHMENT
  - MANUAL_BROWSER
  - FOIA
ocpr:
  - API
  - OFFICIAL_BULK_EXPORT
  - TRANSITION_REPORT
  - BUDGET_ATTACHMENT
  - SEARCH_INDEX
  - ARCHIVE
  - MANUAL_BROWSER
  - FOIA
usaspending:
  - API
  - AWARD_DATA_ARCHIVE
  - FPDS_REPORT_BUILDER
  - SEARCH_INDEX
  - MANUAL_BROWSER
