name: Semgrep

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "29 3 * * 3"

permissions:
  contents: read

jobs:
  semgrep:
    uses: jotaele44/thehub-pr/.github/workflows/semgrep.yml@ae8a245a6847b7538490b8a741aa62f177231623
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
